# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  Publish:
    name: Publish Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Extract Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Determine Package to Publish
        id: set_package
        run: |
          if [[ "${TAG_NAME}" == openfortkit-v* ]]; then
            echo "PACKAGE_DIR=packages/create-openfortkit" >> $GITHUB_ENV
          elif [[ "${TAG_NAME}" == openfortjs-v* ]]; then
            echo "PACKAGE_DIR=packages/create-openfort-js" >> $GITHUB_ENV
          elif [[ "${TAG_NAME}" == v* ]]; then
            echo "PACKAGE_DIR=packages/create-openfort" >> $GITHUB_ENV
          else
            echo "No matching package found for tag ${TAG_NAME}"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn
        run: corepack prepare yarn@4.4.1 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Configure npm for Authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ${{ env.PACKAGE_DIR }}
