name: Quality Check
on: [pull_request]
env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
jobs:
  lint:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Node v16
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 16

      - name: Use node_modules cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install deps
        run: yarn

      - name: Build the code
        run: yarn build

      - name: Run ESLint
        run: yarn lint
