name: Quality Check
on: [pull_request]
env:
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
jobs:
  lint:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Node v20
      - uses: actions/setup-node@v4.3.0
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn

      - name: Build Project
        run: yarn build

      - name: Lint Code
        run: yarn lint
