name: Quality Check
on: [pull_request]

jobs:
  lint:
    name: Quality Check
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_IMMUTABLE_INSTALLS: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack for Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint
